### ISSUE TITLE
gene list for GO term in Figure 1 

### ISSUE THREAD

**Issue by M0hammadL** [scCOVID-19/COVIDPBMC#2]
Hi

thanks for this amazing work and also for making the data and code the code public! 

I am looking for gene lists used to calculate Interferon response in figure 1d, I could not find which genes you exactly used or the code for that here or gene list somewhere.

I greatly appreciate your help here.

**Comment by zktuong** [comment]
hi @M0hammadL, i believe the code would be very similar to what is shown in https://github.com/scCOVID-19/COVIDPBMC/blob/69d1047eb8fd1f775acabb9d8453452853076dde/myeloid/myeloid_signature_scoring_publish.ipynb
but using the entire dataset. @greynolds81 could perhaps give more information.
