### ISSUE TITLE
geneset for B cells annotation

### ISSUE THREAD

**Issue by yulicarp** [scCOVID-19/COVIDPBMC#7]
Hi,

thanks for this amazing work and also for making the code public.

I am looking for gene lists used to calculate B cells signatures in `021821_NewcastleSangerCambridge_QC.ipynb`, I could not find which genes you exactly used.

I greatly appreciate your help here.

**Comment by zktuong** [comment]
hi, you should be able to find those genesets here:
https://github.com/tuonglab/tuonglab_genesets/tree/main/Bcells
